name: shopping_list
description: "Synced shopping list PWA."

publish_to: "none"

version: 1.2.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  cupertino_modal_sheet: ^1.1.0
  device_preview: ^1.1.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.3
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  mcquenji_firebase:
    git:
      url: https://github.com/mcquenji/mcquenji_firebase.git
  pwa_update_listener: ^0.1.0
  qr_flutter: ^4.1.0
  share_plus: ^9.0.0
  super_cupertino_navigation_bar: ^2.1.2
  timeago: ^3.6.1

dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^3.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

dependency_overrides:
  device_preview:
    git:
      url: https://github.com/RuslanTsitser/flutter_device_preview
      path: device_preview
  mcquenji_firebase:
    path: ../mcquenji_firebase

flutter:
  uses-material-design: true
  generate: true
