name: shopping_list
description: "Synced shopping list PWA."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.3
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  mcquenji_firebase:
    git:
      url: https://github.com/mcquenji/mcquenji_firebase.git
  super_cupertino_navigation_bar: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.9
  # flutter_gen: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
