name: Quality Assurance
on:
  pull_request: 
    types: 
        - opened
        - synchronize
    branches: 
        - main

jobs:
    static-analysis:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.6

            - name: Read .fvmrc
              id: fvmrc
              uses: ActionsTools/read-json-action@v1.0.5
              with:
                file_path: .fvmrc
        
            - name: Set up Flutter
              uses: subosito/flutter-action@v2.16.0
              with:
                flutter-version: ${{ steps.fvmrc.outputs.flutter }}

            - name: Get dependencies
              run: flutter pub get

            - name: Analyze code
              continue-on-error: true # The check will fail on the 'Annotate results' step if there are any errors
              run: flutter analyze --no-pub >> analysis.txt
              
            - name: Setup Python
              uses: actions/setup-python@v5.1.0
              with:
                python-version: '3.10'

            - name: Comment results
              run: python .github/workflows/construct_analysis_comment.py analysis.txt ${{ github.event.pull_request.head.sha }} ${{ github.event.number }} comment.txt
              #                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
              #                                        Apparently, GitHub automatically appends github.com/owner/repo/pull/ the url when rendering comments
            - name: Post comment
              uses: peter-evans/create-or-update-comment@v4.0.0
              with:
                body-path: comment.txt
                issue-number: ${{ github.event.pull_request.number }}

            - name: Annotate results
              uses: invertase/github-action-dart-analyzer@v3