name: Quality Assurance
on:
  pull_request: 
    types: 
        - opened
        - synchronize
    branches: 
        - LP-156-Frontend-Refactor # Temporary. Will be changed to `app` when refactor is complete

permissions:
    checks: write
    pull-requests: write

jobs:
    static-analysis:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Read .fvmrc
              id: flutter_version
              run: echo "::set-output name=fvmrc::$(cat .fvmrc)"
            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                flutter-version: ${{ fromJson(steps.flutter_version.outputs.fvmrc).flutter }}
            - name: Get dependencies
              run: flutter pub get
            - name: Analyze code
              continue-on-error: true # The check will fail on the 'Annotate results' step if there are any errors
              run: flutter analyze --no-pub >> analysis.txt
            - name: Setup Python
              uses: actions/setup-python@v4.7.1
              with:
                python-version: '3.10'
            - name: Comment results
              run: python .github/workflows/construct_analysis_comment.py analysis.txt ${{ github.event.pull_request.head.sha }} ${{ github.event.number }} comment.txt
              #                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
              #                                        Apparently, GitHub automatically appends github.com/owner/repo/pull/ the url when rendering comments
            - name: Post comment
              uses: peter-evans/create-or-update-comment@v3.1.0
              with:
                body-path: comment.txt
                issue-number: ${{ github.event.pull_request.number }}
            - name: Annotate results
              uses: invertase/github-action-dart-analyzer@v2.0.0