name: Bump Version

on:
    pull_request: 
        branches: main
        paths-ignore: 
            - 'README.md'
            - 'CHANGELOG.md'
        types: closed

jobs:
    bump-version:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.6
            - name: Configure committer
              run: |
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"
            - name: Bump version
              uses: qzb/standard-version-action@v1.0.5
    